### ISSUE TITLE
Unable to finish the installation

### ISSUE THREAD

**Issue by viktor-borysiuk** [ip2location/IP2Location-Varnish#6] opened 2023-02-27 10:29 UTC
Hey there, 

I am building the varnish image on my local environment and getting the next error
<img width="1391" alt="изображение" src="https://user-images.githubusercontent.com/89019299/221539607-17d85930-62bd-4c94-bdac-6fe4d244e46b.png">

Will be much appriciated if someone can help me with that!

**Comment by viktor-borysiuk** [comment] 2023-02-28 07:51
A short update, tried to get the latest changes from the repository (master branch) which contains varnish 7.x compatibility and got a bit another error:

<img width="1389" alt="изображение" src="https://user-images.githubusercontent.com/89019299/221788129-bded58d2-0fd7-4107-903b-1afd19182501.png">

Varnish version
<img width="588" alt="изображение" src="https://user-images.githubusercontent.com/89019299/221788200-b6f0cf67-5bc0-4645-8aaa-a8e1796f74a4.png">

**Comment by ip2location** [comment] 2023-04-10 07:58
Hi viktor-borysiuk,

We have tried on our machine, but we couldn't reproduce the issue. However, we found out that the issue may occurred because of missing varnish-dev package. If you didn't install this package yet, can you please try install it first before try again?

**Comment by ip2location** [comment] 2024-05-14 07:31
Hi @viktor-borysiuk,

We haven’t heard back from you in a while, and the issue seems to have stalled. Therefore, we’re going to close this issue for now.

If you are still experiencing this problem or have more details to provide, please feel free to reopen the issue or create a new one with the updated information.

**Closed by ip2location** 2024-05-14 07:31 UTC
